// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Author struct {
	AuthorID *string `json:"author_id"`
	Name     string  `json:"name"`
	Mail     *string `json:"mail"`
}

type AuthorInput struct {
	Name string  `json:"name"`
	Mail *string `json:"mail"`
}

type Book struct {
	Name    string  `json:"name"`
	BookID  *string `json:"book_id"`
	Genre   *string `json:"genre"`
	Authors string  `json:"authors"`
}

type BookInput struct {
	Name    string  `json:"name"`
	Genre   *string `json:"genre"`
	Authors *string `json:"authors"`
}

type DeleteStatus struct {
	Iserror     bool    `json:"iserror"`
	Description *string `json:"description"`
}

type Genre struct {
	GenreID *string `json:"genre_id"`
	Name    *string `json:"name"`
}

type GenreInput struct {
	Name string `json:"name"`
}

type GetAuthor struct {
	Isexists bool    `json:"isexists"`
	Author   *Author `json:"author"`
}

type GetBook struct {
	Isexists bool  `json:"isexists"`
	Book     *Book `json:"book"`
}

type GetGenre struct {
	Isexists bool   `json:"isexists"`
	Genre    *Genre `json:"genre"`
}

type PostStatus struct {
	Iserror     bool    `json:"iserror"`
	Description *string `json:"description"`
	ID          *string `json:"id"`
}

type PutStatus struct {
	Iserror     bool    `json:"iserror"`
	Description *string `json:"description"`
}

type UpdateAuthorInput struct {
	Name *string `json:"name"`
	Mail *string `json:"mail"`
}

type UpdateBookInput struct {
	BookID  string  `json:"book_id"`
	Name    *string `json:"name"`
	Genre   *string `json:"genre"`
	Authors *string `json:"authors"`
}

type UpdateGenreInput struct {
	GenreID string  `json:"genre_id"`
	Name    *string `json:"name"`
}
